previewsEnabled: true

databases:
  - name: myrailssite
    databaseName: myrailssite
    user: myrailssite

services:
  - type: web
    name: myrailssite
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    initialDeployHook: ./bin/init_deploy.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myrailssite
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
    domains:
      - three.heyhey.co.uk
      - four.heyhey.co.uk
      - five.heyhey.co.uk
      - six.heyhey.co.uk

envVarGroups:      
  - name: blueprint-test
    envVars:
      - key: RENKEY
        sync: false