previewsEnabled: true

databases:
  - name: myrailssiteinit
    databaseName: myrailssiteinit
    user: myrailssiteinit

services:
  - type: web
    name: myrailssiteinit
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    initialDeployHook: ./bin/init_deploy.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myrailssiteinit
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true

envVarGroups:      
  - name: blueprint-test
    envVars:
      - key: RENKEY
        sync: false